name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Check out source repository
        uses: actions/checkout@v4

      - name: 📦 Set up uv
        uses: astral-sh/setup-uv@v5

      - name: ✅ ruff check
        run: uvx ruff check --ignore F401 --line-length 120 custom_components/

      - name: ✅ ruff format check
        run: uvx ruff format --check custom_components/

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        continue-on-error: true
        uses: hacs/action@main
        with:
          category: integration
